project_name: "Splashy Frogs"
tagline: "Sink your opponents with explosive coconuts. A Global Game Jam 2017 game."
project_url: "https://github.com/aschearer/robotfrog"
latest_release_url: "https://github.com/aschearer/robotfrog/releases/latest"